export const IMAGE_URLS = {
  DAN_DA_DAN: 'https://m.media-amazon.com/images/M/MV5BMmE4NGI0NWUtOGFmNS00Yzk4LWFjYWYtYjU2MTAxYTMxMGQ5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  DELICIOUS_IN_DUNGEON: 'https://m.media-amazon.com/images/M/MV5BNmU3ZGFhMmYtNzczYy00NTE0LThkYjgtNWFiYTY2NzRkM2QzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  FRIEREN: 'https://m.media-amazon.com/images/M/MV5BZTI4ZGMxN2UtODlkYS00MTBjLWE1YzctYzc3NDViMGI0ZmJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  KAIJU_NO_8: 'https://m.media-amazon.com/images/M/MV5BYjNjNTczNmItOWRkNi00MWQ0LWI1OWYtYTFlNTllMDFjZjg3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  SOLO_LEVELING: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/93/Solo_Leveling_season_2_key_visual.jpg/250px-Solo_Leveling_season_2_key_visual.jpg',
  APOTHECARY_DIARIES: 'https://m.media-amazon.com/images/M/MV5BNjAxMmFjZjgtYjM1ZS00NzdmLTliZDktZmIyMzU5YTBlNDBmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  HAIKYU: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQKlYs1lQsPElSDl4S504hTeN8cLgcGRJRRmfqiXobsRLkzbJzhIrQNYa4p1ix4SO0DWeUI',
  LOOK_BACK: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Look_Back_%28%E3%83%AB%E3%83%83%E3%82%AF%E3%83%90%E3%83%83%E3%82%AF%2C_2024%29_film_poster.jpg',
  MONONOKE: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Mononoke_Paper_Umbrella_Film_Poster.jpg',
  MHA_MOVIE: 'https://m.media-amazon.com/images/M/MV5BNGVmZDJhNjItYzdlOC00ODA2LWFkYjctY2NmMzNiZTQ2NTVjXkEyXkFqcGc@._V1_.jpg',
  SPY_FAMILY_MOVIE: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ0j1aquPSZymD_TKLg3PdMuvwyVmcIj2tK-lEmWj1UMAphtjHrWxMx03ymFB2O5NThICFlxg',
  COLORS_WITHIN: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgjxb7F9yaVevjc__6GOyJju8LBATTP3TyLyFS3NYW6fYXhuryDMA2W5PenNIH9dk8C0Li8w',
  BLEACH: 'https://m.media-amazon.com/images/M/MV5BMjgyM2QzMjAtOGZjOS00OGFkLTkxZGYtMDJjZGM5MzIzYmM3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  DEMON_SLAYER: 'https://demonslayer-anime.com/hta/assets/img/img_kv.jpg',
  MHA_SEASON7: 'https://a.storyblok.com/f/178900/1064x1596/d057641427/my-hero-academia-season-7-key-art-tall.png/m/filters:quality(95)format(webp)',
  ONE_PIECE: 'https://external-preview.redd.it/one-piece-anime-going-on-break-returning-april-2025-v0-eAfnmFuSst07MCSMmNjQ8jHWr3i3CmWsYgbs057RedE.jpg?width=640&crop=smart&auto=webp&s=3156f60eab0be615b09d2d9f329120d45f0c0ade',
  OSHI_NO_KO: 'https://static.wikia.nocookie.net/shipping/images/f/f8/Oshi_no_Ko.png/revision/latest?cb=20231219101756',
  SPY_FAMILY_SEASON2: 'https://upload.wikimedia.org/wikipedia/en/b/b9/SPY%C3%97FAMILY_Season_2_Vol_1.png',
  PLUTO: 'https://resizing.flixster.com/sJZcxGSWqAwrweziFZR0ddUs7sk=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vZWUwNzEzY2EtOGQ1OC00MTE5LWFhNGYtM2Q5YTY5Y2JmZWI4LmpwZw==',
  KONOSUBA: 'https://upload.wikimedia.org/wikipedia/en/8/85/KonoSuba_season_3_KV.jpg',
  MUSHOKU_TENSEI: 'https://cdn2.penguin.com.au/covers/original/9798888434352.jpg',
  REZERO: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcStrjdUj-PcRqdxxeqRF34vQglD4C9GoJMNZCfAPMQzArZdIFKg',
  SHANGRI_LA: 'https://static0.cbrimages.com/wordpress/wp-content/uploads/sharedimages/2024/09/shangri-la-frontier.jpg',
  SUICIDE_SQUAD: 'https://upload.wikimedia.org/wikipedia/en/6/69/Suicide_Squad_Isekai_key_visual.jpg',
  SLIME: 'https://m.media-amazon.com/images/M/MV5BOTczMjM3MDUtYmZjMC00YzZhLWE4ODQtNjg5YWU4NTJjNzY2XkEyXkFqcGc@._V1_.jpg',
  KAFKA: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGnmNvQI-Mta81lEACW-dPB77pP3ZRePFSLw&s',
  OKARUN: 'https://c4.wallpaperflare.com/wallpaper/438/755/606/dandadan-okarun-anime-hd-wallpaper-preview.jpg',
  MAOMAO: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Maomao_%28The_Apothecary_Diaries%29.png',
  MOMO: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXY5yk1zb5J-FyIDRWn7q0Rwooy17kEEml5g&s',
  SUNG_JINWOO: 'https://4kwallpapers.com/images/wallpapers/sung-jinwoo-solo-2732x2732-17972.jpg',
  ABYSS: 'https://www.roughtrade.com/_next/image?url=https%3A%2F%2Fcdn.shopify.com%2Fs%2Ffiles%2F1%2F0867%2F1120%2F6219%2Ffiles%2FGOEnTXOWgAAJegV_7ee8444e_thumbnail_4096.jpg%3Fv%3D1726875138&w=3840&q=75',
  BLING_BANG: 'https://i.scdn.co/image/ab67616d0000b273952e61594d2a003089d8d318',
  FATAL: 'https://upload.wikimedia.org/wikipedia/en/e/ef/Gemn_-_Fatal.png',
  LEVEL: 'https://ogre.natalie.mu/media/news/comic/2023/1101/orelevel_5.jpg?impolicy=m&imwidth=750&imdensity=1',
  OTONOKE: 'https://upload.wikimedia.org/wikipedia/en/2/20/Creepy_Nuts_-_Otonoke.png',
  THE_BRAVE: 'https://i1.sndcdn.com/artworks-EVMtlIfp3Kf4-0-t500x500.jpg',
} as const;

export const ROUTES = {
  HOME: '/',
  CATEGORIES: '/categories',
  AUTH: '/auth',
  PROFILE: '/profile',
} as const;

export const COLORS = {
  BACKGROUND: '#1a1a1a',
  CARD_BACKGROUND: '#242424',
  BORDER: '#333333',
  ACCENT: '#FFD700',
  ACCENT_HOVER: '#FFE44D',
  TEXT_PRIMARY: '#FFFFFF',
  TEXT_SECONDARY: '#CCCCCC',
} as const; 